### ISSUE TITLE
[Bug] GRPC error when syncing edge

### ISSUE THREAD

**Issue by AndreMaz** [thingsboard/thingsboard-edge#46] opened 2023-03-09 21:08 UTC
**Describe the bug**

When I press "Sync Edge" I can see in logs of TB edge the following error:

  tb-edge  2023-03-09 20:57:49,080 [grpc-default-executor-0] WARN  o.t.edge.rpc.EdgeGrpcClient - [024b44dd-ece4-c8ca-5302-b61fdca7cffb] Stream was terminated due to error:
 tb-edge  io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR
 tb-edge        at io.grpc.Status.asRuntimeException(Status.java:535)
 tb-edge        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
 tb-edge        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
 tb-edge        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
 tb-edge        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
 tb-edge        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
 tb-edge        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
 tb-edge        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
 tb-edge        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
 tb-edge        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
 tb-edge        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
 tb-edge        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 tb-edge        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 tb-edge        at java.base/java.lang.Thread.run(Thread.java:829)
 tb-edge  2023-03-09 20:57:52,083 [cloud-manager-reconnect-57-thread-1] INFO  o.t.s.s.cloud.CloudManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR!

**Note 1** It manages to sync the Widgets, Users and device profiles but fails to sync the actual devices.

**Note 2** TB cloud does not show any errors in the logs

**Environment**

 * ThingsBoard: Docker Image v3.4.4 (Link: https://hub.docker.com/layers/thingsboard/tb-postgres/3.4.4/images/sha256-9338fc2a02595531992878b1f68f8354a6f31d0dd08c51e0212afe1838aef28e?context=explore ) 
 * ThingsBoard Edge:  Docker image v3.4.3 (Link https://hub.docker.com/layers/thingsboard/tb-edge/3.4.3EDGE/images/sha256-20fd55472de22ddc012b8dbee380ccb7ba3c037dde09e01082678c2934a92171?context=explore )

**Additional context**
It's a brand new deployment of TB edge 3.4.3

**Comment by volodymyr-babak** [comment] 2023-03-10 15:10
@AndreMaz 

could you please attach logs from your docker containers of thingsboard and tb-edge?

**Comment by volodymyr-babak** [comment] 2023-03-10 19:54
@AndreMaz 

Could you please send me full tb-edge.log and thingsboard.log files? 
And additionally please send your tb-edge.conf and thingsboard.conf files (If you are using docker please send me your docker compose files)?
I suppose something is wrong in the configuration of connectivity. 
Looks like you enabled SSL on edge side and do not enabled it on the cloud or something similar.
Please send me these files to vbabak@thingsboard.io.

Thanks.

**Comment by AndreMaz** [comment] 2023-03-14 09:20
Hi @volodymyr-babak 

> Looks like you enabled SSL on edge side and do not enabled it on the cloud or something similar.

Yes, the SSL is enabled on TB-Edge but not enabled on TB-Cloud because it's located behind Kong (reverse proxy) and SSL is enabled in Kong. However, I don't think that the source of the problem is the SSL as some data successfully arrives to TB-Edge.

Here's a print of "Downlinks" tab @ TB-Cloud
![image](https://user-images.githubusercontent.com/9802754/224949903-c31f807a-c960-4a06-9dff-a5f780118546.png)

and here's a print of "Cloud Events" @ TB-Edge
![image](https://user-images.githubusercontent.com/9802754/224950373-436dc6cc-8205-4707-890a-069cc8e6c70d.png)

and a print of "Status" of TB-Edge
![image](https://user-images.githubusercontent.com/9802754/224951765-5d40c0b5-56f3-4857-9689-c3c9b3a60ed6.png)


Here's another print of "Customer Users" @ TB-Edge, which are successfully synced.
![image](https://user-images.githubusercontent.com/9802754/224950883-0f0dce79-e9c7-439b-8b82-ff018f087124.png)

In addition to users, TB-Edge instance manages to sync the Widgets and Device Profiles. However, it fails to sync the Dashboards and the Devices

Re the docker files. Unfortunately, I can't provide them for the TB-cloud as we're using Pulumi to manage our infrastructure.

**Comment by volodymyr-babak** [comment] 2023-03-14 10:10
@AndreMaz 

thanks for the provided information. Indeed issue is not in SSL because you are receiving and sending events.
Could you please check size of your dashboards that are assigned to the Edge?
We have opened issue in case dashboard size is bigger 4 MB: 
https://github.com/thingsboard/thingsboard-edge/issues/41

Maybe that could be the root cause for your case as well.

Additionally, please provide me full logs file of the edge service at least - maybe I can see root cause from the edge log file.

**Comment by AndreMaz** [comment] 2023-03-14 11:08
Hi @volodymyr-babak 

> Could you please check size of your dashboards that are assigned to the Edge?
> We have opened issue in case dashboard size is bigger 4 MB:

I don't think that it's source of the problem as total size of my 7 dashboards is 1.4MB

> Additionally, please provide me full logs file of the edge service at least - maybe I can see root cause from the edge log file.

Here's the tb-edge log file [tb-edge.2023-03-09.0.log](https://github.com/thingsboard/thingsboard-edge/files/10967593/tb-edge.2023-03-09.0.log)

**Comment by volodymyr-babak** [comment] 2023-03-14 20:30
@AndreMaz 

thanks for the logs, but root cause is not clear yet.
Looks like really something is in the message size - probably edge is trying to send something that is bigger 4 MB or something like that.
Without logs from the server side it's hard to provide you exact answer what is wrong. 
Could you please request server side logs from your provider?

**Comment by AndreMaz** [comment] 2023-03-14 21:03
Hi @volodymyr-babak

That you for the quick response.
I'll try to get the info that you need tomorrow. 

> Looks like really something is in the message size - probably edge is trying to send something that is bigger 4 MB or something like that.

I think that gRPC only has a limit of 4MBs for the incoming messages so it must be the TB-Cloud that's pushing something big (Tb-edge instance is empty as I've wiped all volumes) 

One question, TB-Cloud syncs all DB tables with the TB-Edge, right? If so then I might be able to take a look at the DB and check if there's anything larger than 4MBs.

**Comment by volodymyr-babak** [comment] 2023-03-15 08:09
hi @AndreMaz 

not exactly. Cloud syncs to the edge only entities, that are assigned to these edge. 
Additionally, cloud syncs all device profiles, queues and some other generic stuff from the tenant level to the edge of this tenant. 
But cloud never sync all DB directly to the edge.

**Comment by volodymyr-babak** [comment] 2023-04-10 13:36
Closing ticket - root cause of the issue was in the miss configuration of connection string of gateway device.

**Closed by volodymyr-babak** 2023-04-10 13:36 UTC
Labels: bug
