### ISSUE TITLE
[Question] Can shared attribute updated at thingsboard dashbaord passed to device via edge?

### ISSUE THREAD

**Issue by Xwoder** [thingsboard/thingsboard-edge#25] opened 2022-08-30 07:01 UTC
**Component**

 * Generic

**Description**
I have a thingsboard, an edge, a device and they are connected well.

The relation of them are showed below:

```
thingsboard <-> edge <-> device
```

I created a dashboard in the thingsboard. There is an `update shared integer attribute` widget which can change a shared attribute named `offset` in it.

After I changed the value of the attribute in the widget, the value of the attribute will be changed in the edge synchronously. I could see it changed at the `Attributes` tab of the device.

But the device which has already subscribed the attribute didn't received the changes of the attributes.

 On the other hand, If I changed the value of the attribute not in thingsboard dashboard but in edge dashboard, it will work properly, the device could received the changes of the value of the attribute.

So, is there any point I missed? May be I need to modify the rule chain or change same configuration?

**Environment**

 * OS:  macOS 11.6.8
 * ThingsBoard: 3.4.1
 * ThingsBoard Edge: 3.4.1
 * Browser: Microsoft Edge 104.0.1293.70

**Comment by volodymyr-babak** [comment] 2022-08-30 13:43
@Xwoder 

thanks for posting this question. 
At the moment shared attribute subscription works only for the local updates.
But this is a valid improvement, that should be added to the edge in future releases.
We are going to design this feature and provide an update on the expected release of version 3.4.2 or 3.5.

**Comment by volodymyr-babak** [comment] 2022-10-26 15:47
The issue is going to be resolved in the 3.4.2 release.
Changes are already committed: 
https://github.com/thingsboard/thingsboard-edge/commit/bd58775a40364138e6d78a15f2f86d0b3e1e1efd

**Closed by volodymyr-babak** 2022-10-26 15:47 UTC
Labels: question
