### ISSUE TITLE
Cloud events efficiency seems to be very slow

### ISSUE THREAD

**Issue by WingedKitten** [thingsboard/thingsboard-edge#44] opened 2023-03-01 08:43 UTC
How can I improve his speed?

I only access the 19 sets of equipment, they once every 5 seconds to send data

But after a period of time the edge and thingsboard data latency for eight hours

**Environment**

 * centos:7.9
 * ThingsBoard: 3.4.3
 * Thingsboard-edge: 3.4.3

![image](https://user-images.githubusercontent.com/96456666/222087802-2dfcd447-78f1-4e84-922b-c9f17c9f4d5a.png)

**Comment by WingedKitten** [comment] 2023-03-01 08:55
@volodymyr-babak

**Comment by volodymyr-babak** [comment] 2023-03-01 11:47
@WingedKitten 

hello, so in your case your 19 devices send timeseries data only every 5 seconds and you have lag on edge side for 8 hours?
Here are the default setting for the batch size and timeout to send data to cloud:
https://thingsboard.io/docs/edge/user-guide/install/config/#cloud-parameters

![image](https://user-images.githubusercontent.com/3466101/222130715-33916f3d-9899-4c79-a3aa-cef66ccf6b8c.png)

So every single second edge is able  to send 50 messages to the cloud.
I believe that the root cause not in this configuration, but somewhere else.
Could you please attach logs from your edge instance and from your cloud instance as well?

**Comment by WingedKitten** [comment] 2023-03-02 01:51
I checked the network, memory, and bandwidth, utilization rate is very low, I adjusted the CLOUD_RPC_STORAGE_MAX_READ_RECORDS_COUNT parameters, its speed faster, it should be the problem。
Thanks for your reply

**Comment by volodymyr-babak** [comment] 2023-03-04 09:56
@WingedKitten closing the issue. Please reopen in case you'll face any new issues with performance.

**Closed by volodymyr-babak** 2023-03-04 09:56 UTC
Labels: question
