### ISSUE TITLE
Deleting old TB Edge PostgreSQL data

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard-edge#28] opened 2022-09-22 11:13 UTC
Hi, 

I have set up a TB Edge instance along with PostgreSQL DB by using the docker on Linux using instructions: https://thingsboard.io/docs/user-guide/install/edge/docker/

Following is my system architecture for testing the TB GW, Edge, and Cloud Server: 
![image](https://user-images.githubusercontent.com/35078099/191729320-e8737c98-c458-4894-885f-23dd0658f398.png)

I am currently sending the simulated data to 6 devices on the Edge. I want to delete the data from 2 devices older than 3 years and delete the data from other devices older than 4 months. In this regard, I have tested the TTL parameter value from the Timeseries node in the rule chain by following the instructions from the source https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-timeseries-node.

So far, I have found that this TTL value has no effect on the time series data and I can clearly see all the previous data from the local dashboard. 

Furthermore, I have found that we can specify the data cleanup interval in the docker configuration, source: https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters.

Question: Is there a way to clean the previous data from TB Edge? If yes, can we specify a different data cleanup interval for different devices? Is there some set of instructions on how to modify the docker container configuration to fix this issue?

Thanks

**Comment by volodymyr-babak** [comment] 2022-09-23 09:02
Hello @akseerali 

TTL parameter in Timeseries node is only applicable for Cassandra Database. 
PostgreSQL database doesn't have functionality for custom TTL on a specific row entry.
Edge is designed to connect to PostgreSQL only, and that's why custom TTL per device is not available on edge.
You can have custom TTL per device only in the case of the ThingsBoard server that is connected to Cassandra Database as time-series data. 
Currently, the only way to clean up data on the edge is to set TTL for the entire ts_kv table by modifying SQL configuration parameters:
https://thingsboard.io/docs/edge/user-guide/install/config/#sql-configuration-parameters

Please search for SQL_TTL_TS_TS_KEY_VALUE_TTL. By default, this parameter value is 0, and records in the ts_kv table are never expired. If you'll add this parameter to your docker image configuration - ts records are going to be removed according to this configuration.

**Comment by akseerali** [comment] 2022-09-23 12:23
Hi @volodymyr-babak,

Thanks for the information. So, based on the information in the given link, I have modified the configuration in 'yaml' file as:

`version: '2.2'
services:
  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:3.4.0EDGE"
    ports:
      - "18080:8080"
      - "11883:1883"
      - "15683-15688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres1:5432/tb-edge
      CLOUD_ROUTING_KEY: 61309c3d-beb9-42cb-cf5a-b65a7bab579b
      CLOUD_ROUTING_SECRET: e1iedrjdj3qx1f6ix5hm # e.g. bztvkvfqsye7omv9uxlp
      CLOUD_RPC_HOST: demo.thingsboard.io
    volumes:
      - ~/.mytb-edge-data:/data
      - ~/.mytb-edge-logs:/logs

  postgres1:
    restart: always
    image: "postgres:12"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
      SQL_TTL_TS_ENABLED: true
      SQL_TTL_TS_EXECUTION_INTERVAL: 3600000
      SQL_TTL_TS_TS_KEY_VALUE_TTL: 1800
    volumes:
      - ~/.mytb-edge-data/db:/var/lib/postgresql/data`




However, I still can't see any change in the data. Please have a look, thanks.

**Comment by volodymyr-babak** [comment] 2022-09-24 13:15
@akseerali 

please add 

`SQL_TTL_TS_ENABLED: true`
`SQL_TTL_TS_EXECUTION_INTERVAL: 3600000`
`SQL_TTL_TS_TS_KEY_VALUE_TTL: 1800`

to the **mytbedge** container(instead of postgres1) and wait for 1 hour (3600000 milliseconds) before the timeseries clean-up procedure will be started. 
Your data should be cleaned up after 1 hour of edge service was restarted.

**Comment by akseerali** [comment] 2022-09-26 10:37
Hi @volodymyr-babak,

Thanks a lot for the information. I am now able to delete the old data from Devices; however, the data in Assets still appears. Please have a look at the attached figure below:

![image](https://user-images.githubusercontent.com/35078099/192256020-907bd6a4-f129-4a7a-8a93-e7640972a9fe.png)

Is there a method to clean the data from all the fields simultaneously? 

Thanks

**Comment by volodymyr-babak** [comment] 2022-10-03 07:51
hi @akseerali 

here is the source code of the procedure, that removes ts data:
https://github.com/thingsboard/thingsboard-edge/blob/v3.4/dao/src/main/resources/sql/schema-ts-psql.sql

Please scroll to **cleanup_timeseries_by_ttl**.
As you can see, it removes data for devices and assets:
![image](https://user-images.githubusercontent.com/3466101/193526210-2e848e19-a024-438b-9d50-6073ffa58205.png)

So, by design, your asset data should be removed.

Could you please provide more information on your setup - your asset and devices are on the Tenant level? 
Do the assigned to any customer?

**Comment by akseerali** [comment] 2022-10-10 15:28
Hi @volodymyr-babak,

The old data is able to clear automatically from both the assets and devices. In my second test, I once again made sure to recreate some assets and devices and assign them to the TB Edge. I also checked the database functions to clear the data from the assets and devices and found everything was fine.

**Closed** 2022-10-18 17:27 UTC
